
services:
  backend:
    build: ./back-end
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/chat-app

  frontend:
    build: ./react
    ports:
      - "5173:80"
    depends_on:
      - backend        

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"